const resources = [
    {
        name: "Good Old Forest Story",
        author: "RomaB",
        link: "https://romab.itch.io/forest-story",
        image: require("./images/adventure-forest-story.png"),
        className: "shadow",
        releaseDate: "2022-11-17",
    },
    {
        name: "Faerie Ring",
        author: "Antonio Buch",
        link: "https://buchplays.itch.io/faerie-ring",
        image: require("./images/adventure-faerie-ring.png"),
        className: "shadow",
        releaseDate: "2022-11-14",
    },
    {
        name: "The Whites",
        author: "Josef Adamčík & Anna Marklová",
        link: "https://josefadamcik.itch.io/the-whites",
        image: require("./images/adventure-the-whites.jpg"),
        className: "shadow",
        releaseDate: "2022-11-16",
    },
    {
        name: "It's Rough in the Rough",
        author: "Matthew Morris",
        link: "https://manarampmatt.itch.io/its-rough-in-the-rough",
        image: require("./images/adventure-rough.png"),
        className: "shadow",
        releaseDate: "2022-10-29",
    },
    {
        name: "Shattered Rain",
        author: "Brian Stauffer",
        link: "https://brstf.itch.io/shattered-rain",
        image: require("./images/adventure-shattered-rain.png"),
        className: "shadow",
        releaseDate: "2022-10-25",
    },
    {
        name: "Nightmare Loom",
        author: "Ignis Avis Press",
        link: "https://ignisavis.itch.io/nightmare-loom",
        image: require("./images/adventure-nightmare-loom.png"),
        className: "shadow",
        releaseDate: "2022-10-14",
    },
    {
        name: "Under the Garden",
        author: "Renasdoodles",
        link: "https://super-strawberry.itch.io/under-the-garden",
        image: require("./images/adventure-under-the-garden.png"),
        className: "shadow",
        releaseDate: "2022-10-07",
    },
    {
        name: "Nettle Leaves",
        author: "Monkey’s Paw Games",
        link: "https://monkeys-paw-games.itch.io/nettle-leaves",
        image: require("./images/adventure-nettle-leaves.png"),
        className: "shadow",
        releaseDate: "2022-08-31",
    },
    {
        name: "Tomb of the Slumbering Queen",
        author: "Philippa Mort",
        link: "https://philippa-mort.itch.io/tomb-of-the-slumbering-queen",
        image: require("./images/adventure-tomb-slumbering-queen.png"),
        className: "shadow",
        releaseDate: "2022-08-19",
    },
    {
        name: "Maus Menagerie",
        author: "Colin Chapman",
        link: require("./files/Mausritter_-_Maus_Menagerie_A4.pdf"),
        image: require("./images/adventure-maus-menangerie.png"),
        className: "shadow",
        releaseDate: "2022-08-30",
    },
    {
        name: "The Birch Harvest",
        author: "David Anderson",
        link: "https://verdant-core.itch.io/the-birch-harvest",
        image: require("./images/adventure-birch-harvest.png"),
        className: "shadow",
        releaseDate: "2022-08-23",
    },
    {
        name: "A Time for Mice",
        author: "David Anderson",
        link: "https://verdant-core.itch.io/a-time-for-mice",
        image: require("./images/adventure-time-for-mice.png"),
        className: "shadow",
        releaseDate: "2022-08-26",
    },
    {
        name: "Oakwood",
        author: "Skoro Hrdinové",
        link: "https://skorohrdinove.itch.io/oakwood",
        image: require("./images/adventure-oakwood.png"),
        className: "shadow",
        releaseDate: "2022-08-25",
    },
    {
        name: "Shrine of the Jade Scorpion",
        author: "Paul Ligorski",
        link: "https://heart-of-arcana.itch.io/shrine-of-the-jade-scorpion",
        image: require("./images/adventure-jade-scorpian.png"),
        className: "shadow",
        releaseDate: "2022-05-14",
    },
    {
        name: "Lilliputian: Adventure on the Open Seas",
        author: "ManaRampMatt",
        link: "https://manarampmatt.itch.io/lilliputian",
        image: require("./images/adventure-lilliputian.png"),
        className: "shadow",
        releaseDate: "2022-05-08",
    },
    {
        name: "Perez’s Assignment",
        author: "Antonio Buch",
        link: "https://buchplays.itch.io/perezs-assignment",
        image: require("./images/adventure-perez.png"),
        className: "shadow",
        releaseDate: "2022-03-23",
    },
    {
        name: "Keep It Together",
        author: "Rich Hawkes",
        link: "https://www.drivethrurpg.com/product/379384/Keep-It-Together",
        image: require("./images/adventure-keep-it-together.png"),
        className: "shadow",
        releaseDate: "2022-02-14",
    },
    {
        name: "Rattlepoint City",
        author: "Matthew Stegman",
        link: "https://manarampmatt.itch.io/rattle-point-city",
        image: require("./images/adventure-rattle-point.png"),
        className: "shadow",
        releaseDate: "2022-02-03",
    },
    {
        name: "Crawler Beyond the Stone",
        author: "Brian Stauffer",
        link: "https://brstf.itch.io/crawler-beyond-the-stone",
        image: require("./images/adventure-crawler.png"),
        className: "shadow",
        releaseDate: "2022-02-03",
    },
    {
        name: "Oak Pasture",
        author: "PenPaperDice",
        link: "https://penpaperdice.itch.io/oak-pasture-1",
        image: require("./images/adventure-oak-pasture.png"),
        className: "shadow",
        releaseDate: "2022-01-09",
    },
    {
        name: "The Mountain Lord’s Respite",
        author: "David Lombardo",
        link: "https://awkwardturtle.itch.io/the-badger-lords-respite",
        image: require("./images/adventure-mountain-lord.png"),
        className: "shadow",
        releaseDate: "2021-12-30",
    },
    {
        name: "Inflame The Yellow Crown",
        author: "Brian Stauffer",
        link: "https://brstf.itch.io/inflame-the-yellow-crown",
        image: require("./images/adventure-inflame.png"),
        className: "shadow",
        releaseDate: "2021-11-03",
    },
    {
        name: "Merriweather Wetlands Park",
        author: "ManaRampMatt",
        link: "https://manarampmatt.itch.io/merriweather-wetlands-park",
        image: require("./images/adventure-merriweather.png"),
        className: "shadow",
        releaseDate: "2021-11-30",
    },
    {
        name: "Einzelmaus: Solo Play Rules",
        author: "ManaRampMatt",
        link: "https://manarampmatt.itch.io/einzelmaus-solo-mausritter",
        image: require("./images/adventure-einzelmaus.png"),
        className: "shadow",
        releaseDate: "2021-12-10",
    },
    {
        name: "Bernpyle #8 — Ice Mice",
        author: "ManaRampMatt",
        link: "https://manarampmatt.itch.io/bernpyle-8",
        image: require("./images/adventure-bernpyle-8.png"),
        className: "shadow",
        releaseDate: "2021-11-25",
    },
    {
        name: "Sölverkalt",
        author: "David Lombardo",
        link: "https://awkwardturtle.itch.io/soverkalt",
        image: require("./images/adventure-solverkalt.png"),
        className: "shadow",
        releaseDate: "2021-10-11",
    },
    {
        name: "Sunken Abbey",
        author: "Paul Ligorski",
        link: "https://heart-of-arcana.itch.io/sunken-abbey",
        image: require("./images/adventure-sunken-abbey.png"),
        className: "shadow",
        releaseDate: "2021-10-06",
    },
    {
        name: "The Flood Priest’s Garden",
        author: "ManaRampMatt",
        link: "https://manarampmatt.itch.io/the-flood-priests-garden",
        image: require("./images/adventure-flood-priest.png"),
        className: "shadow",
        releaseDate: "2021-09-24",
    },
    {
        name: "Sanctum of the Ori Magi",
        author: "Brian Stauffer",
        link: "https://brstf.itch.io/ori-magi",
        image: require("./images/adventure-ori-magi.png"),
        className: "shadow",
        releaseDate: "2021-09-16",
    },
    {
        name: "Bat Cultist Lair",
        author: "Paul Ligorski",
        link: "https://heart-of-arcana.itch.io/bat-cultist-lair",
        image: require("./images/adventure-bat-cultist-lair.png"),
        className: "shadow",
        releaseDate: "2021-09-15",
    },
    {
        name: "Queasy Quarry Quest",
        author: "imnotsupposedtogetjigsinit",
        link: "https://notsupposedtogetjigs.itch.io/queasy-quarry-quest",
        image: require("./images/adventure-qqq.jpg"),
        className: "shadow",
        releaseDate: "2021-09-11",
    },
    {
        name: "Bernpyle #6 — Into the Veins of the Earth",
        author: "ManaRampMatt",
        link:
            "https://manarampmatt.itch.io/bernpyle-6-into-the-veins-of-the-earth",
        image: require("./images/adventure-bernpyle-6.png"),
        className: "shadow",
        releaseDate: "2021-07-23",
    },
    {
        name: "The Vitacernis",
        author: "Brian Stauffer",
        link: "https://brstf.itch.io/the-vitacernis",
        image: require("./images/adventure-vitacernis.png"),
        className: "shadow",
        releaseDate: "2021-05-11",
    },
    {
        name: "Alchemy",
        author: "Fortune Trove",
        link: "https://fortunetrove.itch.io/alchemy-supplement",
        image: require("./images/adventure-alchemy.png"),
        className: "shadow",
        releaseDate: "2021-07-06",
    },
    {
        name: "Mayfield",
        author: "Various",
        link: "https://manarampmatt.itch.io/mayfield",
        image: require("./images/adventure-mayfield.jpg"),
        className: "shadow",
        releaseDate: "2021-06-26",
    },
    {
        name: "Chimneyhaus",
        author: "James Hanna",
        link: "https://feylightstudio.com/product/chimneyhaus/",
        image: require("./images/adventure-chimneyhaus.jpg"),
        className: "shadow",
        releaseDate: "2021-06-25",
    },
    {
        name: "Stoneford",
        author: "Juan Carlos Hernández",
        link:
            "https://imsobadatnicknames.itch.io/stoneford-a-location-for-mausritter",
        image: require("./images/adventure-stoneford.png"),
        className: "shadow",
        releaseDate: "2021-02-28",
    },
    {
        name: "Tales from Moonshore",
        author: "Lux, Paige & ManaRampMatt",
        link: "https://manarampmatt.itch.io/tales-from-moonshore",
        image: require("./images/adventure-moonshore.png"),
        className: "shadow",
        releaseDate: "2021-02-27",
    },
    {
        name: "Mouse Supplements",
        author: "Gray Moth",
        link: "https://graymoth.itch.io/mousesupplements",
        image: require("./images/adventure-mouse-supplements-min.png"),
        className: "shadow",
        releaseDate: "2021-02-12",
    },
    {
        name: "A Ghostly Tail",
        author: "Ross Burton",
        link: "https://rossburton.itch.io/a-ghostly-tail",
        image: require("./images/adventure-ghostly-tail.png"),
        className: "shadow",
        releaseDate: "2021-01-13",
    },
    {
        name: "Lost Mines of Salt Pine",
        author: "ekobor",
        link: "https://ekobor.itch.io/lost-mines-of-salt-pine",
        image: require("./images/adventure-lost-mines-saltmarsh.png"),
        className: "shadow",
        releaseDate: "2021-02-09",
    },
    {
        name: "Bernpyle #3",
        author: "ManaRampMatt",
        image: require("./images/adventure-bernpyle-3-min.png"),
        link: "https://manarampmatt.itch.io/bernpyle-issue-3",
        className: "shadow",
        releaseDate: "2021-02-06",
    },
    {
        name: "Belladonna’s Botannicals",
        author: "Juan Carlos Hernández",
        link: "https://imsobadatnicknames.itch.io/belladonnas-botannicals",
        image: require("./images/adventure-botanicals.png"),
        className: "shadow",
        releaseDate: "2021-02-09",
    },
    {
        name: "Zauberei’s Grim Grimoire",
        author: "Greyson Yandt",
        link: "https://greysonwhy.itch.io/zaubereis-grim-grimoire",
        image: require("./images/adventure-grim-grimoire.png"),
        className: "shadow",
        releaseDate: "2021-01-17",
    },
    {
        name: "The Woodshed",
        author: "smcabrera & ekobor",
        link: "https://ekobor.itch.io/the-woodshed",
        image: require("./images/adventure-the-woodshed.png"),
        className: "shadow",
        releaseDate: "2021-01-16",
    },
    {
        name: "The Library War: Queen’s Quest",
        author: "Josh Domanski",
        image: require("./images/adventure-library-war.png"),
        link: "https://unenthuser.itch.io/the-library-war-queens-quest",
        className: "shadow",
        releaseDate: "2020-12-28",
    },
    {
        name: "Fort Ploddy",
        author: "Harrison Swift",
        image: require("./images/adventure-ploddy.png"),
        link: "https://glaucus.itch.io/fort-ploddy",
        className: "shadow",
        releaseDate: "2020-12-28",
    },
    {
        name: "MausRatos #1",
        author: "@mausratos",
        image: require("./images/adventure-mausratos.png"),
        link: "https://mausratosbr.itch.io/mausratos1",
        className: "shadow",
        releaseDate: "2020-12-25",
    },
    {
        name: "A not so Stille Nacht",
        author: "ManaRampMatt",
        image: require("./images/adventure-still-night.png"),
        link: "https://manarampmatt.itch.io/silentnight",
        className: "shadow",
        releaseDate: "2020-12-17",
    },
    {
        name: "Bernpyle #2",
        author: "ManaRampMatt",
        link: "https://manarampmatt.itch.io/bernpyleissue2",
        image: require("./images/adventure-bernpyle-2.png"),
        className: "shadow",
        releaseDate: "2020-12-02",
    },
    {
        name: "Thistle Kingdom #2: Winter",
        author: "Christopher Käck",
        image: require("./images/adventure-thistle-kingdom-2.png"),
        link: "https://kejsarmakten.itch.io/thistle-kingdom-2",
        className: "shadow",
        releaseDate: "2020-12-14",
    },
    {
        name: "Bestiarium",
        author: "ManaRampMatt & Mausritter Discord",
        link: "https://manarampmatt.itch.io/beastiarium-mausritter",
        image: require("./images/adventure-beastarium.png"),
        className: "shadow",
        releaseDate: "2020-12-29",
    },
    {
        name: "Bernpyle #1",
        author: "ManaRampMatt",
        link:
            "https://manarampmatt.itch.io/bernpyle-an-unofficial-mausritter-zine",
        image: require("./images/adventure-burrow.png"),
        className: "shadow",
        releaseDate: "2020-10-26",
    },
    {
        name: "Lake of the Pirat King",
        author: "Cameron Donnelly & Richard Davis",
        link: "https://justafatyeti.itch.io/lake-of-the-pirat-king",
        image: require("./images/adventure-lake-pirat.png"),
        className: "shadow",
        releaseDate: "2020-10-26",
    },
    {
        name: "Stonewall",
        author: "Cameron Donnelly & Richard Davis",
        image: require("./images/adventure-stonewall.png"),
        link: "https://justafatyeti.itch.io/stonewall",
        className: "shadow",
        releaseDate: "2020-10-29",
    },
    {
        name: "Thistle Kingdom #1: Summer",
        author: "Christopher Käck",
        image: require("./images/adventure-thistle-kingdom-1.png"),
        link: "https://kejsarmakten.itch.io/thistle-kingdom-1",
        className: "shadow",
        releaseDate: "2020-09-11",
    },
]

export default resources
