const resources = [
    {
        name: 'The Library War: Queen’s Quest',
        author: 'Josh Domanski',
        image: require('./images/adventure-library-war.png'),
        link: 'https://unenthuser.itch.io/the-library-war-queens-quest',
        className: 'shadow',
        releaseDate: '2020-12-28',
    },
    {
        name: 'Fort Ploddy',
        author: 'Harrison Swift',
        image: require('./images/adventure-ploddy.png'),
        link: 'https://unenthuser.itch.io/the-library-war-queens-quest',
        className: 'shadow',
        releaseDate: '2020-12-28',
    },
    {
        name: 'MausRatos #1',
        author: '@mausratos',
        image: require('./images/adventure-mausratos.png'),
        link: 'https://mausratosbr.itch.io/mausratos1',
        className: 'shadow',
        releaseDate: '2020-12-25',
    },
    {
        name: 'A not so Stille Nacht',
        author: 'ManaRampMatt',
        image: require('./images/adventure-still-night.png'),
        link: 'https://manarampmatt.itch.io/silentnight',
        className: 'shadow',
        releaseDate: '2020-12-17',
    },
    {
        name: 'Bernpyle #2',
        author: 'ManaRampMatt',
        link: 'https://manarampmatt.itch.io/bernpyleissue2',
        image: require('./images/adventure-bernpyle-2.png'),
        className: 'shadow',
        releaseDate: '2020-12-02',
    },
    {
        name: 'Thistle Kingdom #2: Winter',
        author: 'Christopher Käck',
        image: require('./images/adventure-thistle-kingdom-2.png'),
        link: 'https://kejsarmakten.itch.io/thistle-kingdom-2',
        className: 'shadow',
        releaseDate: '2020-12-14',
    },
    {
        name: 'Bestiarium',
        author: 'ManaRampMatt & Mausritter Discord',
        link: 'https://manarampmatt.itch.io/beastiarium-mausritter',
        image: require('./images/adventure-beastarium.png'),
        className: 'shadow',
        releaseDate: '2020-12-29',
    },
    {
        name: 'Beastiary - Amphibians',
        author: 'ManaRampMatt & Mausritter Discord',
        link: 'https://graymoth.itch.io/beastiary-amphibians',
        image: require('./images/adventure-beast-amphibians.png'),
        className: 'shadow',
        releaseDate: '2020-12-18',
    },
    {
        name: 'Beastiary - Arachnids',
        author: 'Gray Moth',
        link: 'https://graymoth.itch.io/beastiary-arachnids',
        image: require('./images/adventure-beast-arachnids.png'),
        className: 'shadow',
        releaseDate: '2020-12-12',
    },
    {
        name: 'Player Species',
        author: 'Gray Moth',
        link: 'https://graymoth.itch.io/player-species',
        image: require('./images/adventure-player-species.png'),
        className: 'shadow',
        releaseDate: '2020-12-10',
    },
    {
        name: 'Bernpyle #1',
        author: 'ManaRampMatt',
        link: 'https://manarampmatt.itch.io/bernpyle-an-unofficial-mausritter-zine',
        image: require('./images/adventure-burrow.png'),
        className: 'shadow',
        releaseDate: '2020-10-26',
    },
    {
        name: 'Lake of the Pirat King',
        author: 'Cameron Donnelly & Richard Davis',
        link: 'https://justafatyeti.itch.io/lake-of-the-pirat-king',
        image: require('./images/adventure-lake-pirat.png'),
        className: 'shadow',
        releaseDate: '2020-10-26',
    },
    {
        name: 'Stonewall',
        author: 'Cameron Donnelly & Richard Davis',
        image: require('./images/adventure-stonewall.png'),
        link: 'https://justafatyeti.itch.io/stonewall',
        className: 'shadow',
        releaseDate: '2020-10-29',
    },
    {
        name: 'Thistle Kingdom #1: Summer',
        author: 'Christopher Käck',
        image: require('./images/adventure-thistle-kingdom-1.png'),
        link: 'https://kejsarmakten.itch.io/thistle-kingdom-1',
        className: 'shadow',
        releaseDate: '2020-09-11',
    },
];

export default resources;
