
const CUSTOM_ITEM_IMAGES = [
    { name: 'None', special: 'none', url: 'none' },
    { name: 'Custom...', special: 'upload', url: 'upload' },
    { special: 'divider' },
    { name: 'Torch', url: require('./images/item-torch.png') },
    { name: 'Lantern', url: require('./images/item-lantern.png') },
    { name: 'Electric lantern', url: require('./images/item-electric-lantern.png') },
    { name: 'Pip purse', url: require('./images/item-pips.png') },
    { name: 'Quiver', url: require('./images/item-quiver.png') },
    { name: 'Rations', url: require('./images/item-rations.png') },
    { name: 'Stones', url: require('./images/item-stones.png') },
    { special: 'divider' },
    { name: 'Branch', url: require('./images/item-improvised.png') },
    { name: 'Dagger', url: require('./images/item-light-1.png') },
    { name: 'Needle', url: require('./images/item-light-2.png') },
    { name: 'Axe', url: require('./images/item-medium-1.png') },
    { name: 'Sword', url: require('./images/item-medium-2.png') },
    { name: 'Mace', url: require('./images/item-medium-3.png') },
    { name: 'Warhammer', url: require('./images/item-heavy-1.png') },
    { name: 'Spear', url: require('./images/item-heavy-2.png') },
    { name: 'Hookarm', url: require('./images/item-heavy-3.png') },
    { name: 'Bow', url: require('./images/item-heavy-ranged.png') },
    { name: 'Sling', url: require('./images/item-light-ranged.png') },
    { special: 'divider' },
    { name: 'Heavy armour', url: require('./images/item-heavy-armour.png') },
    { name: 'Light armour', url: require('./images/item-light-armour.png') },
    { special: 'divider' },
    { name: 'Spell 1', url: require('./images/item-spell-1.png') },
    { name: 'Spell 2', url: require('./images/item-spell-2.png') },
    { name: 'Spell 3', url: require('./images/item-spell-3.png') },
    { name: 'Spell 4', url: require('./images/item-spell-4.png') },
    { name: 'Spell 5', url: require('./images/item-spell-5.png') },
];

export default CUSTOM_ITEM_IMAGES;
