const CUSTOM_ITEM_IMAGES = [
    { name: 'None', special: 'none' },
    { name: 'Custom...', special: 'upload' },
    { special: 'divider' },
    { name: 'Torch', url: require('./images/item-torch.png').default },
    { name: 'Lantern', url: require('./images/item-lantern.png').default },
    {
        name: 'Electric lantern',
        url: require('./images/item-electric-lantern.png').default,
    },
    { name: 'Pip purse', url: require('./images/item-pips.png').default },
    { name: 'Quiver', url: require('./images/item-quiver.png').default },
    { name: 'Rations', url: require('./images/item-rations.png').default },
    { name: 'Stones', url: require('./images/item-stones.png').default },
    { special: 'divider' },
    { name: 'Branch', url: require('./images/item-improvised.png').default },
    { name: 'Dagger', url: require('./images/item-light-1.png').default },
    { name: 'Needle', url: require('./images/item-light-2.png').default },
    { name: 'Axe', url: require('./images/item-medium-1.png').default },
    { name: 'Sword', url: require('./images/item-medium-2.png').default },
    { name: 'Mace', url: require('./images/item-medium-3.png').default },
    { name: 'Warhammer', url: require('./images/item-heavy-1.png').default },
    { name: 'Spear', url: require('./images/item-heavy-2.png').default },
    { name: 'Hookarm', url: require('./images/item-heavy-3.png').default },
    { name: 'Bow', url: require('./images/item-heavy-ranged.png').default },
    { name: 'Sling', url: require('./images/item-light-ranged.png').default },
    { special: 'divider' },
    {
        name: 'Heavy armour',
        url: require('./images/item-heavy-armour.png').default,
    },
    {
        name: 'Light armour',
        url: require('./images/item-light-armour.png').default,
    },
    { special: 'divider' },
    { name: 'Spell 1', url: require('./images/item-spell-1.png').default },
    { name: 'Spell 2', url: require('./images/item-spell-2.png').default },
    { name: 'Spell 3', url: require('./images/item-spell-3.png').default },
    { name: 'Spell 4', url: require('./images/item-spell-4.png').default },
    { name: 'Spell 5', url: require('./images/item-spell-5.png').default },
    {
        name: 'Spell (blank)',
        url: require('./images/item-spell-blank.png').default,
    },
];

export default CUSTOM_ITEM_IMAGES;
