const CUSTOM_ITEM_TEMPLATES = [
    {
        name: 'Item',
        template: {
            name: 'New item',
            usage: 3,
            damage: '',
            mechanicDetail: '',
            clearDetail: '',
            classDetail: '',
            image: '',
            backgroundColor: '#ffffff',
            foregroundColor: '#000000',
            width: 1,
            height: 1,
            divider: true,
            border: true,
            star: false,
        },
        controls: {
            name: true,
            usage: true,
            image: true,
        },
    },
    {
        name: 'Weapon',
        template: {
            name: 'Sword',
            usage: 3,
            damage: 'd6/d8',
            mechanicDetail: '',
            clearDetail: '',
            classDetail: 'Medium',
            image: 'Sword',
            backgroundColor: '#ffffff',
            foregroundColor: '#000000',
            width: 1,
            height: 1,
            divider: true,
            border: true,
            star: false,
        },
        controls: {
            name: true,
            usage: true,
            damage: true,
            classDetail: true,
            image: true,
        },
    },
    {
        name: 'Armour',
        template: {
            name: 'Heavy armour',
            usage: 3,
            damage: '1 def',
            mechanicDetail: '',
            clearDetail: '',
            classDetail: 'Heavy',
            image: 'Heavy armour',
            backgroundColor: '#ffffff',
            foregroundColor: '#000000',
            width: 1,
            height: 2,
            divider: true,
            border: true,
            star: false,
        },
        controls: {
            name: true,
            usage: true,
            damage: true,
            classDetail: true,
            image: true,
        },
    },
    {
        name: 'Spell',
        template: {
            name: 'Restore',
            usage: 3,
            damage: '',
            mechanicDetail: '',
            clearDetail: '',
            classDetail: '',
            image: 'Spell 1',
            backgroundColor: '#ffffff',
            foregroundColor: '#000000',
            width: 1,
            height: 1,
            divider: true,
            border: true,
            star: true,
        },
        controls: {
            name: true,
            usage: true,
            image: true,
        },
    },
    {
        name: 'Condition',
        template: {
            name: 'Injured',
            usage: 0,
            damage: '',
            mechanicDetail: 'Disadvantage on STR & DEX saves',
            clearDetail: 'After full rest',
            classDetail: '',
            image: '',
            backgroundColor: '#ff4444',
            foregroundColor: '#000000',
            width: 1,
            height: 1,
            divider: false,
            border: true,
            star: false,
        },
        controls: {
            name: true,
            mechanicDetail: true,
            clearDetail: true,
        },
    },
    {
        name: 'Freeform',
        template: {},
        controls: {
            name: true,
            usage: true,
            damage: true,
            mechanicDetail: true,
            clearDetail: true,
            classDetail: true,
            star: true,
            image: true,
        },
    },
];

export default CUSTOM_ITEM_TEMPLATES;
