
export const BACKGROUNDS = [
    [
        'Test subject',
        { name: 'Magic missile', type: 'Spell' },
        { name: 'Lead coat', type: 'Heavy armour', shape: 'tall', def: '1 def' },
    ],
    [
        'Kitchen forager',
        { name: 'Shield and jerkin', type: 'Light armour', shape: 'wide', def: '1 def' },
        { name: 'Cookpots' },
    ],
    [
        'Cage dweller',
        { name: 'Be understood', type: 'Spell' },
        { name: 'Bottle of milk' },
    ],
    [
        'Hedge witch',
        { name: 'Heal', type: 'Spell' },
        { name: 'Incense stick' },
    ],
    [
        'Leatherworker',
        { name: 'Shield and jerkin', type: 'Light armour', shape: 'wide', def: '1 def' },
        { name: 'Shears' },
    ],
    [
        'Street tough',
        { name: 'Dagger', type: 'Light', attack: 'd6' },
        { name: 'Flask of coffee' },

    ],
    [
        'Mendicant priest',
        { name: 'Restore', type: 'Spell' },
        { name: 'Holy symbol' },
    ],
    [
        'Beetleherd',
        { name: 'Hireling: Loyal beetle', type: 'special' },
        { name: 'Pole, 6"' },
    ],
    [
        'Ale brewer',
        { name: 'Hireling: Drunken torchbearer', type: 'special' },
        { name: 'Small barrel of ale' },
    ],
    [
        'Fishermouse',
        { name: 'Needle', type: 'Light', attack: 'd6' },
        { name: 'Net' },
    ],
    [
        'Blacksmith',
        { name: 'Hammer', type: 'Medium', attack: 'd6/d8' },
        { name: 'Metal file' },
    ],
    [
        'Wireworker',
        { name: 'Wire, spool' },
        { name: 'Electric lantern', usage: 6 },
    ],
    [
        'Woodcutter',
        { name: 'Axe', type: 'Medium', attack: 'd6/d8' },
        { name: 'Twine, roll' },
    ],
    [
        'Bat cultist',
        { name: 'Darkness', type: 'Spell' },
        { name: 'Bag of bat teeth' },
    ],
    [
        'Tin miner',
        { name: 'Pickaxe', type: 'Medium', attack: 'd6/d8' },
        { name: 'Lantern' },
    ],
    [
        'Trash collector',
        { name: 'Hammer', type: 'Heavy', attack: 'd10', shape: 'tall' },
        { name: 'Mirror' },
    ],
    [
        'Wall rover',
        { name: 'Fishhook' },
        { name: 'Thread, spool' },
    ],
    [
        'Merchant',
        { name: 'Hireling: Pack rat', type: 'special' },
        { name: '20p IOU from a noblemouse' },
    ],
    [
        'Raft crew',
        { name: 'Hammer', type: 'Medium', attack: 'd6/d8' },
        { name: 'Wooden spikes' },
    ],
    [
        'Worm wrangler',
        { name: 'Pole, 6"' },
        { name: 'Soap' },
    ],
    [
        'Sparrow rider',
        { name: 'Fishhook' },
        { name: 'Goggles' },
    ],
    [
        'Sewer guide',
        { name: 'Metal file' },
        { name: 'Thread, spool' },
    ],
    [
        'Prison guard',
        { name: 'Spear', type: 'Heavy', attack: 'd10', shape: 'tall' },
        { name: 'Chain, 6"' },
    ],
    [
        'Fungus farmer',
        { name: 'Dried mushroom' },
        { name: 'Spore mask' },
    ],
    [
        'Dam builder',
        { name: 'Shovel' },
        { name: 'Wooden spikes' },
    ],
    [
        'Cartographer',
        { name: 'Quill & ink' },
        { name: 'Compass' },
    ],
    [
        'Trap thief',
        { name: 'Block of cheese' },
        { name: 'Glue' },
    ],
    [
        'Vagabond',
        { name: 'Tent', shape: 'tall' },
        { name: 'Treasure map, dubious' },
    ],
    [
        'Grain farmer',
        { name: 'Spear', type: 'Heavy', attack: 'd10', shape: 'tall' },
        { name: 'Whistle' },
    ],
    [
        'Message runner',
        { name: 'Bedroll' },
        { name: 'Documents, sealed' },
    ],
    [
        'Troubadour',
        { name: 'Musical instrument' },
        { name: 'Disguise kit' },
    ],
    [
        'Gambler',
        { name: 'Loaded dice' },
        { name: 'Mirror' },
    ],
    [
        'Sap tapper',
        { name: 'Bucket' },
        { name: 'Wooden spikes' },
    ],
    [
        'Bee keeper',
        { name: 'Jar of honey' },
        { name: 'Net' },
    ],
    [
        'Librarian',
        { name: 'Scrap of obscure book' },
        { name: 'Quill & ink' },
    ],
    [
        'Pauper noblemouse',
        { name: 'Felt hat' },
        { name: 'Perfume' },
    ],
];

export const FIRST_NAMES = [
    'Ada',
    'Agate',
    'Agnes',
    'Aloe',
    'April',
    'Azalea ',
    'Bay',
    'Belladonna ',
    'Blossom',
    'Brie ',
    'Brynn',
    'Cherry',
    'Claire',
    'Crocus',
    'Dahlia ',
    'Daisy',
    'Else',
    'Emerald',
    'Erin',
    'Grace',
    'Gwendoline',
    'Hazel',
    'Heather',
    'Hette',
    'Holly',
    'Hyacinth',
    'Iris',
    'Juniper',
    'Lavender',
    'Lily',
    'Magnolia ',
    'Marigold',
    'Marjoram ',
    'Myrtle',
    'Odette',
    'Olive',
    'Opal',
    'Pearl',
    'Pepper',
    'Poppy',
    'Rosemary',
    'Rue',
    'Saffron ',
    'Sandy',
    'Sassafras ',
    'Shale',
    'Susan',
    'Thistle',
    'Violet',
    'Willow',
    'Alder',
    'Ambrose',
    'Anise',
    'Annotto ',
    'August',
    'Avens',
    'Basil',
    'Beryl',
    'Birch',
    'Boldo ',
    'Bill',
    'Burdock',
    'Butter',
    'Cassia',
    'Chicory',
    'Clive',
    'Colby',
    'Dill',
    'Eared',
    'Edmund',
    'Elmer',
    'Ernest',
    'Fennel',
    'Festus',
    'Francis',
    'Gil',
    'Hawthorn ',
    'Heath',
    'Horatio',
    'Jack',
    'Jasper',
    'Konrad',
    'Larkspur',
    'Laurel',
    'Lorenz',
    'Mace',
    'Oliver',
    'Orin',
    'Reepicheep',
    'Rowan',
    'Simon',
    'Sorrel',
    'Stilton',
    'Tarragon ',
    'Warren ',
    'Wattle',
    'Wattle',
    'Whitacre',
    'Wormwood',
    'Yarrow',
];

export const LAST_NAMES = [
    'Baiter',
    'Black',
    'Buckthorne',
    'Burley',
    'Butterball',
    'Catreizen',
    'Danger',
    'Deerider',
    'Grant',
    'Halva',
    'Maker',
    'Pipp',
    'Ratschlappe',
    'Seedfall',
    'Snow',
    'Summerholme',
    'Tunneler',
    'White',
    'Winterholme',
    'Witter',
];

export const BIRTH_SIGNS = [
    ['Star', 'Brave / Reckless'],
    ['Wheel', 'Industrious / Unimaginative'],
    ['Acorn', 'Inquisitive / Stubborn'],
    ['Storm', 'Generous / Wrathful'],
    ['Moon', 'Wise / Mysterious'],
    ['Mother', 'Nurturing / Worrying'],
];

export const COAT_COLORS = [
    'Chocolate',
    'Black',
    'White',
    'Tan',
    'Grey',
    'Blue',
];

export const COAT_PATTERNS = [
    'solid',
    'brindle',
    'patchy',
    'banded',
    'marbled',
    'flecked',
];

export const PHYSICAL_DETAIL = [
    'Scarred body',
    'Corpulent body',
    'Skeletal body',
    'Willowy body',
    'Tiny body',
    'Massive body',
    'War paint',
    'Foreign clothes',
    'Elegant clothes',
    'Patched clothes',
    'Fashionable clothes',
    'Unwashed clothes',
    'Missing ear',
    'Lumpy face',
    'Beautiful face',
    'Round face',
    'Delicate face',
    'Elongated face',
    'Groomed fur',
    'Dreadlocks',
    'Dyed fur',
    'Shaved fur',
    'Frizzy fur',
    'Silky fur',
    'Night black eyes',
    'Eyepatch',
    'Blood red eyes',
    'Wise eyes',
    'Sharp eyes',
    'Luminous eyes',
    'Cropped tail',
    'Whip-like tail',
    'Tufted tail',
    'Stubby tail',
    'Prehensile tail',
    'Curly tail',
];
